### ISSUE TITLE
No effect in Ubuntu 19.04 / Chrome 78.0.3904.108 (Official Build) (64-bit).

### ISSUE THREAD

**Issue by e3rd** [hempe/ctrlZoom#1]
I left the default options

![image](https://user-images.githubusercontent.com/6942231/69589953-2ffd8b80-0fee-11ea-91ae-bc34a24e0106.png)

I am collecting errors at chrome://extensions/?id=indpmklmjbcfkbnbhoknlggplddednhp

![image](https://user-images.githubusercontent.com/6942231/69589868-c8dfd700-0fed-11ea-98ec-173413738f7e.png)

But I see no error at chrome://extensions/

![image](https://user-images.githubusercontent.com/6942231/69589905-f9277580-0fed-11ea-8bfc-061ab4338a20.png)

I tried both edge scrolling and two-finger scrolling in the system menu:
![image](https://user-images.githubusercontent.com/6942231/69589880-d72df300-0fed-11ea-8bda-67df71d26594.png)

I am holding Ctrl a scrolling on the touchpad but just the page gets scrolled down/up.

**Comment by mbernasocchi** [comment]
You probably need to remove the disabled check box and restart chromium/chrome. I'm on ubuntu 19.10 and after that it worked

**Comment by hempe** [comment]
@e3rd 
The default values were not set correctly in version 1.3.
I fixed the default values, now it is "enabled" by default, and changed the UI to better show if the extension is disabled.
So the default value for all check boxes are not set correctly. In 1.3.
1.4 is currently in review by google. (in the mean time "toggle" the disable flag shoud fix it)

**Comment by e3rd** [comment]
AMAZING! Sorry I was dumb, I was reading the parameters name but I missed it :D
Great plugin!
